events { worker_connections 1024; }

http {
    upstream mis_servicios {
        # Docker Compose creará una red interna donde los nombres de servicios actúan como IPs
        server app1:3000;
        server app2:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://mis_servicios;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
